version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4001:4001"
    depends_on:
      - api 

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "4002:4002"


